# Generated by Django 4.2.2 on 2024-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0005_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
