# Generated by Django 4.2.2 on 2024-04-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0006_user_email_status_user_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=100)),
            ],
        ),
    ]
