# Generated by Django 4.2.2 on 2024-04-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0007_tempuser"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email_status",),
        migrations.RemoveField(model_name="user", name="otp",),
    ]
