# Generated by Django 4.2.2 on 2024-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[("KG", "Kilogram"), ("PC", "Piece")],
                default="KG",
                max_length=2,
                null=True,
            ),
        ),
    ]
